/**
 * Downloads the three typefaces into `src/fonts/` and writes a local
 * `fonts.css`, so the deployed site makes **no** external requests at all.
 *
 * The handoff loads them from Google Fonts and says to self-host in production;
 * this is that step, kept as a script so the files can be refreshed and their
 * provenance is obvious.
 *
 *   npm run fetch:fonts
 *
 * All three are SIL Open Font License 1.1, which permits redistribution.
 * Only the latin and latin-ext subsets are kept — the UI is English and card
 * names stay inside them.
 */
import fs from "node:fs";
import path from "node:path";
import { isMain, repoRoot } from "./lib/paths.ts";

const fontsDir = path.join(repoRoot, "src", "fonts");

// A modern browser UA is required, or the API serves ttf instead of woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/** Variable axes where available, so one file covers every weight we use. */
const CSS_URL =
  "https://fonts.googleapis.com/css2" +
  "?family=Archivo:wght@400..700" +
  "&family=IBM+Plex+Mono:wght@400;500;600" +
  "&family=Newsreader:opsz,wght@6..72,400..500" +
  "&display=swap";

const KEEP_SUBSETS = ["latin", "latin-ext"];

interface FaceBlock {
  subset: string;
  css: string;
  url: string;
}

function parseFaces(css: string): FaceBlock[] {
  const faces: FaceBlock[] = [];
  // Each @font-face is preceded by a /* subset */ comment.
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  for (let m = pattern.exec(css); m !== null; m = pattern.exec(css)) {
    const [, subset = "", block = ""] = m;
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    if (!url) continue;
    faces.push({ subset, css: block, url });
  }
  return faces;
}

function fileNameFor(face: FaceBlock): string {
  const family = /font-family:\s*'([^']+)'/.exec(face.css)?.[1] ?? "font";
  const weight = (/font-weight:\s*([^;]+)/.exec(face.css)?.[1] ?? "400").trim().replace(/\s+/g, "-");
  const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `${slug}-${weight}-${face.subset}.woff2`;
}

async function main(): Promise<void> {
  fs.mkdirSync(fontsDir, { recursive: true });

  const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
  const css = await res.text();

  const faces = parseFaces(css).filter((f) => KEEP_SUBSETS.includes(f.subset));
  if (faces.length === 0) throw new Error("No matching @font-face blocks — the CSS format changed.");

  const seen = new Set<string>();
  const out: string[] = [
    "/* Self-hosted so the deployed site makes no external requests.",
    " * Generated by `npm run fetch:fonts` — edit that script, not this file.",
    " *",
    " * Archivo, IBM Plex Mono and Newsreader are SIL Open Font License 1.1.",
    " * See src/fonts/OFL.txt.",
    " */",
    "",
  ];

  for (const face of faces) {
    const name = fileNameFor(face);
    if (!seen.has(name)) {
      const binary = await fetch(face.url, { headers: { "User-Agent": UA } });
      if (!binary.ok) throw new Error(`${face.url} responded ${binary.status}`);
      fs.writeFileSync(path.join(fontsDir, name), Buffer.from(await binary.arrayBuffer()));
      seen.add(name);
      console.log(`  ${name}`);
    }
    out.push(face.css.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url("./${name}")`), "");
  }

  fs.writeFileSync(path.join(fontsDir, "fonts.css"), `${out.join("\n")}\n`, "utf8");
  const bytes = [...seen].reduce((sum, f) => sum + fs.statSync(path.join(fontsDir, f)).size, 0);
  console.log(`${seen.size} font files, ${(bytes / 1024).toFixed(0)} kB total → ${fontsDir}`);
}

if (isMain(import.meta.url)) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
